"""
Daniel Baer
09.05.2026

mINF4/1, V04, Task 1 "Visualization with Graphviz"

aufgabe1_visualisierung.py

This script loads seq0.txt, inserts values into a Binary Search Tree,
calls graph_traversal(), and answers the required structural questions.
"""

import os
import sys
from pathlib import Path

# Resolve local directories relative to this task folder.
TASK_DIR = Path(__file__).resolve().parent
V04_DIR = TASK_DIR.parent
ALGODAT_DIR = V04_DIR.parent / "AlgoDatSoSe26"
GRAPHVIZ_DOT = V04_DIR / "Graphviz-14.1.5-win64" / "bin" / "dot.exe"

# Add the lecture project path so imports from AlgoDatSoSe26 work from this folder.
sys.path.insert(0, str(ALGODAT_DIR))

from utils.algo_context import AlgoContext  # type: ignore[import-not-found]
from vorlesung.L05_binaere_baeume.bin_tree import BinaryTree  # type: ignore[import-not-found]
import vorlesung.L05_binaere_baeume.bin_tree as bin_tree_module  # type: ignore[import-not-found]


def configure_graphviz() -> None:
    """Configure Graphviz executable from V04 local installation on Windows."""
    if GRAPHVIZ_DOT.exists():
        os.environ["GRAPHVIZ_DOT"] = str(GRAPHVIZ_DOT)
        os.environ["PATH"] = str(GRAPHVIZ_DOT.parent) + os.pathsep + os.environ.get("PATH", "")


def redirect_graph_output_to_task_folder() -> None:
    """Patch path(...) used inside BinaryTree.graph_traversal to write into this folder only."""

    def local_path(filename: str) -> Path:
        return TASK_DIR / filename

    bin_tree_module.path = local_path


def load_seq0() -> list[int]:
    """Read seq0 values from the shared data folder."""
    seq_file = ALGODAT_DIR / "data" / "seq0.txt"
    with seq_file.open("r", encoding="utf-8") as f:
        return [int(line.strip()) for line in f if line.strip()]


def build_tree(values: list[int]) -> BinaryTree:
    """Build a BinaryTree by inserting values in file order."""
    ctx = AlgoContext()
    tree = BinaryTree(ctx)
    for value in values:
        tree.insert(value)
    return tree


def count_leaves(node) -> int:
    """Count leaf nodes recursively."""
    if node is None:
        return 0
    if node.left is None and node.right is None:
        return 1
    return count_leaves(node.left) + count_leaves(node.right)


def latest_pdf_in_task_folder() -> Path:
    """Return the newest BinaryTree PDF generated by graph_traversal in this folder."""
    pdfs = sorted(TASK_DIR.glob("BinaryTree_*.gv.pdf"), key=lambda p: p.stat().st_mtime)
    if not pdfs:
        raise FileNotFoundError("No BinaryTree PDF was generated in task folder 1.")
    return pdfs[-1]


def write_answers(root_value: int, leaf_count: int, height: int, pdf_file: Path) -> None:
    """Write required answers to antworten.txt in this task folder."""
    answer_file = TASK_DIR / "antworten.txt"
    answer_file.write_text(
        "Task 1 - Visualization with Graphviz\n"
        f"Generated PDF: {pdf_file.name}\n"
        f"Root node: {root_value}\n"
        f"Number of leaf nodes: {leaf_count}\n"
        f"Tree height: {height}\n",
        encoding="utf-8",
    )


def main() -> None:
    configure_graphviz()
    redirect_graph_output_to_task_folder()

    values = load_seq0()
    tree = build_tree(values)

    if tree.root is None:
        print("The input sequence is empty.")
        return

    tree.graph_traversal()
    pdf_file = latest_pdf_in_task_folder()

    root_value = tree.root.value
    leaf_count = count_leaves(tree.root)
    height = tree.root.height()

    write_answers(root_value, leaf_count, height, pdf_file)

    print(f"Input values: {len(values)}")
    print(f"PDF output: {pdf_file}")
    print(f"Root node: {root_value}")
    print(f"Leaf nodes: {leaf_count}")
    print(f"Tree height: {height}")


if __name__ == "__main__":
    main()
